backend/luna/server/associated/forms.py
from luna.server.profile.forms import PersonForm
from wtforms import BooleanField, StringField, PasswordField
from wtforms.validators import DataRequired, Length, EqualTo


class AssociatedForm(PersonForm):
    create_user = BooleanField('Criar Usuário')
    contact = StringField('Contato', [DataRequired(message='O campo Contato é obrigatório')])
    # username = StringField('Nome de Usuário', [Length(min=6, max=40)])
    # password = PasswordField('Senha', [Length(min=6, max=40)])
    # confirm = PasswordField(
    #     'Confirmação',
    #     validators=[
    #         DataRequired(),
    #         EqualTo(
    #             'password', message='A confirmação deve ser igual à senha informada.')
    #     ]
    # )

backend/luna/server/associated/views.py
from flask import render_template, Blueprint, url_for, \
    redirect, flash, request
from flask_login import login_required, current_user
from luna.server.associated.forms import AssociatedForm
from luna.server.models import Person, User, Role
from luna.server.repositories import PersonRepository, PeopleAssociatedRepository, \
    UserRepository
from brazilnum.util import clean_id


associated_blueprint = Blueprint('associated', __name__,)


@associated_blueprint.before_request
def admin_not_welcome():
    if current_user.is_authenticated and current_user.has_role(Role.ADMIN):
        return redirect(url_for('admin.index'))


person_repository = PersonRepository()
person_associated_repository = PeopleAssociatedRepository()

@associated_blueprint.route('/associados', methods=['GET', 'POST'])
@login_required
def index():
    form = AssociatedForm()
    return render_template('associated/form.html',form=form)


@associated_blueprint.route('/associados/adicionar', methods=['GET', 'POST'])
@login_required
def add():
    if request.method == 'GET':
        return redirect(url_for('associated.index'))

    form = AssociatedForm()

    if form.validate_on_submit():

        person = Person()

        form.populate_obj(person)
        person.cpf = clean_id(person.cpf)
        phone = clean_id(form.contact.data)
        
        person = dict(person)
        person['emails'] = [form.email.data]
        person['contacts'] = [{
            'ddd': phone[0:2],
            'num': phone[2:]
        }]
        person['city_id'] = None

        if form.create_user.data:
            user = User(
                username=form.email.data,
                password='mudar@123'
            )

            user = UserRepository().create(user)

            person['user_id'] = user.id
        
        person = person_repository.create(person)
        person_associated_repository.create(dict(person_id=current_user.person.id, associated_id=person.id))

        flash('Associado adicionado com sucesso!', 'success')


    return render_template('associated/form.html', form=form)

@associated_blueprint.route('/associados/visualizar/<person_id>', methods=['GET'])
@login_required
def show(person_id):
    person = person_repository.find(person_id)
    return render_template('associated/modals/show.html', person=person)

@associated_blueprint.route('/associados/editar/<person_id>', methods=['GET', 'POST'])
@login_required
def edit(person_id):

    person = person_repository.find(person_id)
    form = AssociatedForm(obj=person)

    if request.method == 'GET':
        email = next(person.emails, None)
        form.email.data = email.email if email else ''
        contact = next(person.contacts, None)
        form.contact.data = '{}{}'.format(contact.ddd, contact.num) if contact else ''
        return render_template('associated/modals/edit.html', form=form, person_id=person_id)

    if form.validate_on_submit():
        form.populate_obj(person)

        person.cpf = clean_id(person.cpf)
        phone = clean_id(form.contact.data)

        person = dict(person)
        person['emails'] = [form.email.data]
        person['contacts'] = [{
            'ddd': phone[0:2],
            'num': phone[2:]
        }]

        person = person_repository.update(person_id, person)

        flash('Associado atualizado com sucesso!', 'success')
    else:
        print(form.errors)
        return render_template('associated/form.html',form=form, person_id=person_id, error_edit=True)

    return redirect(url_for('associated.index'))

@associated_blueprint.route('/associados/excluir/<associated_id>', methods=['GET', 'POST'])
@login_required
def delete(associated_id):

    person_id = current_user.person.id
    person = person_repository.find(associated_id)

    if request.method == 'GET':
        return render_template('associated/modals/delete.html', person=person, person_id=associated_id)

    if request.method == 'POST':
        person_associated_repository.deleteAssociation(person_id, associated_id)

        if not person.user_id:
            person_repository.delete(associated_id)

        flash('Associado removido com sucesso!', 'success')

    return redirect(url_for('associated.index'))

backend/luna/client/templates/associated/form.html
{% extends "_base.html" %} {% block content %}

<div class="ui right floated teal labeled icon button add">
  Adicionar Associado
  <i class="add icon"></i>
</div>

<h2 class="ui header">
  Associados
  <div class="sub header">Gerencie seus associados</div>
</h2>



<section class="room">
  <table class="ui blue table">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Email</th>
        <th>Telefone</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      {% for person in current_user.person.associated %}
        <tr data-id="{{ person.id }}">
          <td>{{ person.name }}</td>
          <td>
              {% for email in person.emails %}
                {{ email.email }} <br>
            {% else %}
              <span>Não informado</span>
            {% endfor %}
          </td>
          <td>
              {% for contact in person.contacts %}
              <span data-mask="(00) 0 0000-0000">{{ contact.ddd }}{{ contact.num }}</span><br />
            {% else %}
              <span>Não informado</span>
            {% endfor %}
          </td>
          <td>
            <button class="ui green basic button show">Visualizar</button>
            {% if not person.user_id %}
              <button class="ui blue basic button edit">Editar</button>
            {% endif %}
            <button class="ui red basic button delete">Excluir</button>
          </td>
        </tr>
        {% else %}
          <tr>
            <td>Não foi cadastrado nenhum associado para o seu perfil.</td>
          </tr>
        {% endfor %}

    </tbody>
  </table>
</section>

<form class="ui small form {{ 'error' if not error_edit and form.errors else '' }} modal add"  action="{{ url_for('associated.add')}}" method="post">
  <i class="close icon"></i>
  <div class="header">
    Adicionar Associado
  </div>
  <div class="ui content">
    <div class="ui error message">
      {% for (field, errors) in form.errors.items() %}
        {% for error in errors %}
          <li>{{error}}</li>
        {% endfor %}
      {% endfor %}
    </div>
    {{ form.hidden_tag() }}

      <div class="field required {{ 'error' if form.name.errors else '' }}">
        {{ form.name.label }}
        {{ form.name(placeholder=form.name.label.text) }}
      </div>
      <div class="two fields">
        <div class="field required {{ 'error' if form.cpf.errors else '' }}">
          {{ form.cpf.label }}
          {{ form.cpf(placeholder=form.cpf.label.text, data_mask='000.000.000-00') }}
        </div>
        <div class="field required {{ 'error' if form.birth.errors else '' }}">
          {{ form.birth.label }}
          {{ form.birth(placeholder=form.birth.label.text, data_mask='00/00/0000') }}
        </div>
      </div>
      <div class="field required {{ 'error' if form.email.errors else '' }}">
        {{ form.email.label }}
        {{ form.email(placeholder=form.email.label.text) }}
      </div>
      <div class="field required {{ 'error' if form.contact.errors else '' }}">
        {{ form.contact.label }}
        {{ form.contact(placeholder=form.contact.label.text, data_mask='(00) 0 0000-0000') }}
      </div>
      <div class="ui segment">
        <div class="ui checkbox">
          {{ form.create_user }}
          {{ form.create_user.label }}
        </div>
      </div>
  </div>
  <div class="actions">
    <div class="ui cancel button">
      Cancelar
    </div>
    <div class="ui green submit button">
      Adicionar
    </div>
  </div>
</form>

<div class="ajax modals">
  {% if error_edit %}
    {% include 'associated/modals/edit.html' %}
  {% endif %}
</div>


{% endblock %}
{% block js %}
  <script src="{{url_for('static', filename='js/associated.js')}}" type="text/javascript"></script>
{% endblock %}