backend/luna/server/main/views.py
# luna/server/main/views.py

from flask_login import login_required, current_user
from flask import render_template, Blueprint, redirect, url_for, flash, request
from luna.server.models import Role
from luna.server.main.forms import NewModuleForm
from luna.server.repositories import ModuleRepository
from collections import defaultdict

main_blueprint = Blueprint('main', __name__,)


@main_blueprint.before_request
def admin_not_welcome():
    if current_user.is_authenticated and current_user.has_role(Role.ADMIN):
        return redirect(url_for('admin.index'))


@main_blueprint.route('/')
@login_required
def dashboard():
    person_id = current_user.person.id if current_user.has_role(Role.COMMON) else current_user.person.associated_to.id
    modules = ModuleRepository().allByPerson(person_id)
    modules_by_room = defaultdict(list)
    for module in modules:
        modules_by_room[module.room].append(module)
    return render_template('main/dashboard.html',form=NewModuleForm(),modules_by_room=modules_by_room)


@main_blueprint.route('/modulo/adicionar', methods=['POST'])
@login_required
def module_add():
    form = NewModuleForm()

    if form.validate_on_submit():
        module_repository = ModuleRepository()
        module = module_repository.findByIdentifier(form.identifier.data)

        form.populate_obj(module)

        module.person_id = current_user.person.id

        module_repository.update(module.id, module)

        flash('Módulo adicionado com sucesso!', 'success')
    return redirect(url_for('main.dashboard'))


@main_blueprint.route('/pedido', methods=['POST'])
@login_required
def help():
    flash('Pedido de ajuda enviado à todos os associados. Aguente firme!', 'success')
    return redirect(url_for('main.dashboard'))

backend/luna/client/templates/_base.html
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <title>Luna Web{% block title %}{% endblock %}</title>
    <!-- meta -->
    <meta name="description" content="Sua assistente pessoal.">
    <meta name="author" content="Luna Org.">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- styles -->
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.10/semantic.min.css" rel="stylesheet">
    <link href="{{url_for('static', filename='main.css')}}" rel="stylesheet" media="screen">
    {% block css %}{% endblock %}
  </head>

  <body>

    {% include 'header.html' %}

    <main>
      <div class="ui container">

        {% if current_user and current_user.person and not current_user.person.associated_to %}
        <button class="ui big red help button">
          Pedido de Socorro
        </button>
        {% endif %}

        <!-- messages -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="ui {{ category }} message">
          <i class="close icon"></i>
          {{message}}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}


        <!-- child template -->
        {% block content %}{% endblock %}

        <br>

        <!-- errors -->
        {% if error %}
          <p class="error"><strong>Error:</strong> {{ error }}</p>
        {% endif %}

      </div>
    </main>

    <br><br>

    {% include 'footer.html' %}
    {% if current_user and current_user.person and current_user.person.associated_to %}
    <div id="pedidoAjuda" class="ui small modal">
      <div class="header">
        Pedido de Ajuda
      </div>
      <div class="content">
        <h2 class="ui header">
          <i class="warning sign icon"></i>
          <div class="content">
            <div class="sub header">{{current_user.person.associated_to.name}} precisa de sua ajuda.</div>
          </div>
        </h2>
      </div>
      <div class="actions">
        <div class="ui cancel button">
          OK
        </div>
      </div>
    </div>
    {% else %}
    <form id="helpModal" method="post" action="{{url_for('main.help')}}" class="ui small modal">
       <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
      <div class="header">
        Pedido de Ajuda
      </div>
      <div class="content">
        <div class="ui form">
          <div class="field">
            <label for="message">Mensagem</label>
            <textarea id="message" name="message" rows="2" placeholder="Oi, Bruno está precisando de sua ajuda!"></textarea>
          </div>
        </div>
      </div>
      <div class="actions">
        <button type="reset" class="ui cancel button">
          Cancelar
        </button>
        <button type="submit" class="ui green submit button">
          Enviar <span class="countdown">(5)</span>
        </button>
      </div>
    </form>
    {% endif %}

    {% include 'auth/edit_password.html' %}

    <!-- scripts -->
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.10/semantic.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.min.js"></script>
    <script src="https://unpkg.com/push.js@1.0.3/bin/push.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.min.js"></script>
    <script src="{{url_for('static', filename='main.js')}}" type="text/javascript"></script>
    <script>
    $(function() {
      Push.Permission.request();

      let current_user = '{{ current_user.username }}';
      let client = new Paho.MQTT.Client('{{config.BROKER_URL}}', {{config.BROKER_PORT}}, 'luna_web_' + Number(new Date()));
      let timeoutHelp = null;

      $('form#helpModal').modal({
        onShow: function() {
          countdownLater();
          $('form#helpModal #message').off('keydown').keydown(function(){
            $('form#helpModal button[type=submit] span.countdown').text('');
            clearTimeout(timeoutHelp);
          });
        },
        onDeny: function() {
          $('form#helpModal button[type=submit] span.countdown').text('('+ 5 +')');
          clearTimeout(timeoutHelp);
          $('form#helpModal #message').off('keydown');
        }
      });

      function countdown() {
        let $form = $('form#helpModal');
        let $countdown = $form.find('button[type=submit] span.countdown');
        let n = Number($countdown.text().replace(/\D/g, '')) - 1;
        if (n <= 0) {
          $form.submit();
        } else {
          $countdown.text('('+ n +')');
          countdownLater();
        }
      }

      function countdownLater() {
        clearTimeout(timeoutHelp);
        timeoutHelp = setTimeout(function() {
          countdown();
        }, 1000);
      }

      $('form#helpModal').submit(function() {
        message = new Paho.MQTT.Message($('form#helpModal #message').val() || 'Este é uma pedido de ajuda padrão.');
        message.destinationName = 'u/' + current_user;
        client.send(message);
      });

      {% if current_user and current_user.person and current_user.person.associated_to %}
      let associado = '{{ current_user.person.associated_to.user.username }}';
      {% else %}
      let associado = undefined;
      {% endif %}

      $('[data-identifier] .checkbox').click(function () {
        let status = $(this).checkbox('is checked');
        let $card = $(this).closest('[data-identifier]');
        message = new Paho.MQTT.Message('1');
        message.destinationName = 'm/' + $card.data('identifier') + '/' + (status ? 101 : 102);
        client.send(message);
        $card.find('.meta').text(status ? 'Ativado' : 'Desativado');
        if (status) {
          $card.find('.module.icon').addClass('blue');
        } else {
          $card.find('.module.icon').removeClass('blue');
        }
      });

      client.onConnectionLost = onConnectionLost;
      client.onMessageArrived = onMessageArrived;

      client.connect({onSuccess:onConnect, useSSL: {{'true' if config.BROKER_SSL else 'false'}}});
      
      function onConnect() {
        if (associado !== undefined) {
          client.subscribe('u/' + associado);
        }

        let identifiers = $('[data-identifier]').map(function() {
          return $(this).data('identifier');
        }).get();

        identifiers.forEach(function(identifier) {
          client.subscribe('m/' + identifier);
          client.subscribe('m/' + identifier + '/+/+');
        });
      }

      function onConnectionLost(responseObject) {
        setTimeout(function() {
          client.connect({onSuccess:onConnect})
        }, 5000);
      }

      function showModal(title, message) {
        let $modal = $('#pedidoAjuda');
        $modal.find('.header .content').contents().first().replaceWith(message);
        $modal.modal('setting', 'closable', false).modal('show');
      }

      function onMessageArrived(message) {
        let topic = message.destinationName;
        let topicValues = topic.split('/');
        let payload = message.payloadString;

        if (topicValues.length === 2) {
          if (associado !== undefined && topicValues[0] === 'u' && topicValues[1] === associado) {
            showModal('Pedido de Ajuda', payload);
            Push.create("Pedido de Ajuda", {
                body: payload,
                icon: '/static/images/logo.png',
                requireInteraction: true,
                onClick: function () {
                    window.focus();
                    this.close();
                }
            });
          } else {
            // testemunho
          }
        } else if (topicValues.length === 3) {
          // comando
        } else if (topicValues.length === 4) {
          let identifier = topicValues[1];
          payload = Number(payload);
          if (Number(topicValues[2]) === 1 && Number(topicValues[3]) === 1) {
            let $card = $('[data-identifier='+identifier+']');
            if (payload === 1) {
              $card.find('.module.icon').addClass('blue');
            } else {
              $card.find('.module.icon').removeClass('blue');
            }
            $card.find('.meta').text(payload === 1 ? 'Ativado' : 'Desativado');
            $card.find('.checkbox').checkbox(payload === 1 ? 'check' : 'uncheck');
          }
        }
      }
    });
    </script>
    {% block js %}{% endblock %}

  </body>
</html>

backend/luna/client/templates/footer.html
<footer>
  <div class="ui center aligned container">
      <span>© <a href="#">Luna Org.</a></span>
  </div>
</footer>

backend/luna/client/templates/header.html
<header>
  <nav class="ui menu">
    <div class="ui container">
      <a href="{{ url_for('main.dashboard') }}" class="item">
        <img class="logo" src="{{url_for('static', filename='images/logo.png')}}" />
      </a>
      {% if current_user.is_authenticated %}
      <div class="right menu">
        <a href="#" class="novo-modulo item">Novo Módulo</a>
        <div class="ui dropdown item">
          {{ current_user.person.first_name or current_user.username }} <i class="dropdown icon"></i>
          <div class="menu">
            <a href="{{ url_for('associated.index')}}" class="item">Associados</a>
            <a href="{{ url_for('profile.profile') }}" class="item">Perfil</a>
            <a href="#" data-target="editPasswordForm" class="item">Alterar senha</a>
            <a href="{{ url_for('auth.logout') }}" class="item">Sair</a>
          </div>
        </div>
      </div>
      {% endif %}
    </div>
  </nav>
</header>