backend/luna/server/user/forms.py
# luna/server/user/forms.py


from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Length, EqualTo


class LoginForm(FlaskForm):
    username = StringField('Nome de Usuário', [DataRequired()])
    password = PasswordField('Senha', [DataRequired()])


class RegisterForm(FlaskForm):
    module = StringField(
        'Identificador do Módulo',
        validators=[
            DataRequired(),
            Length(min=6)
        ]
    )
    username = StringField(
        'Nome do Usuário',
        validators=[
            DataRequired(),
            Length(min=6, max=40)
        ]
    )
    password = PasswordField(
        'Senha',
        validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        'Confirmação',
        validators=[
            DataRequired(),
            EqualTo('password', message='A confirmação deve ser igual à senha informada.')
        ]
    )

backend/luna/server/user/views.py
# luna/server/user/views.py


#################
#### imports ####
#################

from flask import render_template, Blueprint, url_for, \
    redirect, flash, request
from flask_login import login_user, logout_user, login_required

from luna.server import bcrypt
from luna.server.models import User
from luna.server.repositories import UserRepository
from luna.server.user.forms import LoginForm, RegisterForm

################
#### config ####
################

user_blueprint = Blueprint('user', __name__,)


################
#### routes ####
################

@user_blueprint.route('/register', methods=['POST'])
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User(
            username=form.username.data,
            password=form.password.data
        )

        user = UserRepository().create(user)
        login_user(user)

        flash('Você foi cadastrado com sucesso!', 'success')
        return redirect(url_for("main.dashboard"))
    return render_template('user/login.html', login_form=LoginForm(), register_form=form)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = next(UserRepository().findByField(
            'username', form.username.data), None)
        if user and bcrypt.check_password_hash(
                user.password, request.form['password']):
            login_user(user)
            flash('Suas credenciais foram autenticadas com sucesso!', 'success')
            return redirect(url_for('main.dashboard'))
        else:
            flash('Suas credenciais não foram reconhecidas.', 'error')
            return render_template('user/login.html', login_form=form, register_form=RegisterForm())
    return render_template('user/login.html', login_form=form, register_form=RegisterForm())


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Você foi desconectado. Até mais!', 'success')
    return redirect(url_for('user.login'))

backend/luna/client/templates/user/login.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Luna Web</title>
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.10/semantic.min.css" />
  <style>
    body {
      background-color: #eee;
    }

    body>.grid {
      height: 100%;
    }

    .image {
      margin-top: -100px;
    }

    .column {
      max-width: 450px;
    }
  </style>
</head>

<body>
  <div class="ui middle aligned center aligned grid">
    <div class="column">
      <h2 class="ui blue image header">
        <img class="ui image circular" src="{{url_for('static', filename='images/logo.png')}}" />
        <div class="content">
          Luna
        </div>
      </h2>
        
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      {% for category, message in messages %}
      <div class="ui {{ category }} message">
        <i class="close icon"></i>
        {{message}}
      </div>
      {% endfor %}
      {% endif %}
      {% endwith %}
      
      <div class="ui top attached pointing two item menu">
        <a class="item active" data-tab="login">Acessar</a>
        <a class="item" data-tab="register">Registrar-se</a>
      </div>
      
      <form role="form" data-tab="login" method="post" action="" class="ui large login form bottom attached active tab segment">
        {{ login_form.hidden_tag() }}
        
        <div class="field">
          <div class="ui left icon input">
            <i class="user icon"></i>
            {{ login_form.username(placeholder=login_form.username.label.text) }}
          </div>
        </div>
        <div class="field">
          <div class="ui left icon input">
            <i class="lock icon"></i>
            {{ login_form.password(placeholder=login_form.password.label.text) }}
          </div>
        </div>
        <div class="ui fluid large blue submit button">Entrar</div>
        
        <div class="ui error message">
        </div>

      </form>
        
      <form role="form" data-tab="register" method="post" action="{{url_for('user.register')}}" class="ui large register form bottom attached tab segment">
        {{ register_form.hidden_tag() }}
        <div class="field">
          <div class="ui left icon input">
            <i class="barcode icon"></i>
            {{ register_form.module(placeholder=register_form.module.label.text) }}
          </div>
        </div>
        <div class="field">
          <div class="ui left icon input">
            <i class="user icon"></i>
            {{ register_form.username(placeholder=register_form.username.label.text) }}
          </div>
        </div>
        <div class="field">
          <div class="ui left icon input">
            <i class="lock icon"></i>
            {{ register_form.password(placeholder=register_form.password.label.text) }}
          </div>
        </div>
        <div class="field">
          <div class="ui left icon input">
            <i class="lock icon"></i>
            {{ register_form.confirm(placeholder=register_form.confirm.label.text) }}
          </div>
        </div>
        <div class="ui fluid large blue submit button">Cadastrar</div>
        
        <div class="ui error message">
        </div>

      </form>
      
      <div class="ui message">
        Algum problema? <a href="#">Entre em contato!</a>
      </div>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.10/semantic.min.js"></script>
  <script src="{{url_for('static', filename='main.js')}}" type="text/javascript"></script>
  <script>
    $('.ui.login.form').form({
      fields: {
        username: {
          identifier: 'username',
          rules: [{
              type: 'empty',
              prompt: 'Por favor, insira seu nome de usuário'
            }
          ]
        },
        password: {
          identifier: 'password',
          rules: [{
              type: 'empty',
              prompt: 'Por favor, insira sua senha'
            },{
              type: 'length[6]',
              prompt: 'Sua senha deve ter no mínimo 6 caracteres'
            }
          ]
        }
      }
    });
    
    $('.ui.register.form').form({
      fields: {
        module: {
          identifier: 'module',
          rules: [{
            type: 'empty',
            prompt: 'Por favor, identifique seu módulo'
          },{
            type: 'length[6]',
            prompt: 'Identificadores de módulos tem no mínimo 6 caracteres'
          }]
        },
        username: {
          identifier: 'username',
          rules: [{
              type: 'empty',
              prompt: 'Por favor, insira seu nome de usuário'
            }
          ]
        },
        password: {
          identifier: 'password',
          rules: [{
              type: 'empty',
              prompt: 'Por favor, insira sua senha'
            },
            {
              type: 'length[6]',
              prompt: 'Sua senha deve ter no mínimo 6 caracteres'
            }
          ]
        },
        confirm: {
          identifier: 'confirm',
          rules: [{
              type: 'empty',
              prompt: 'Por favor, insira a confirmação da senha'
            }
          ]
        }
      }
    });
    
    $('.ui.menu .item').tab();
  </script>
</body>

</html>