backend/luna/server/associated/forms.py
from luna.server.profile.forms import PersonForm
from wtforms import BooleanField, StringField, PasswordField
from wtforms.validators import DataRequired, Length, EqualTo


class AssociatedForm(PersonForm):
    create_user = BooleanField('Criar Usuário')
    contact = StringField('Contato', [DataRequired(message='O campo Contato é obrigatório')])
    # username = StringField('Nome de Usuário', [Length(min=6, max=40)])
    # password = PasswordField('Senha', [Length(min=6, max=40)])
    # confirm = PasswordField(
    #     'Confirmação',
    #     validators=[
    #         DataRequired(),
    #         EqualTo(
    #             'password', message='A confirmação deve ser igual à senha informada.')
    #     ]
    # )

backend/luna/server/associated/views.py
from flask import render_template, Blueprint, url_for, \
    redirect, flash, request
from flask_login import login_required, current_user
from luna.server.associated.forms import AssociatedForm
from luna.server.models import Person, User, Role
from luna.server.repositories import PersonRepository, PeopleAssociatedRepository, \
    UserRepository
from brazilnum.util import clean_id


associated_blueprint = Blueprint('associated', __name__,)


@associated_blueprint.before_request
def admin_not_welcome():
    if current_user.is_authenticated and current_user.has_role(Role.ADMIN):
        return redirect(url_for('admin.index'))


person_repository = PersonRepository()
person_associated_repository = PeopleAssociatedRepository()

@associated_blueprint.route('/associados', methods=['GET', 'POST'])
@login_required
def index():
    form = AssociatedForm()
    return render_template('associated/form.html',form=form)


@associated_blueprint.route('/associados/adicionar', methods=['GET', 'POST'])
@login_required
def add():
    if request.method == 'GET':
        return redirect(url_for('associated.index'))

    form = AssociatedForm()

    if form.validate_on_submit():

        person = Person()

        form.populate_obj(person)
        person.cpf = clean_id(person.cpf)
        phone = clean_id(form.contact.data)
        
        person = dict(person)
        person['emails'] = [form.email.data]
        person['contacts'] = [{
            'ddd': phone[0:2],
            'num': phone[2:]
        }]
        person['city_id'] = None

        if form.create_user.data:
            user = User(
                username=form.email.data,
                password='mudar@123'
            )

            user = UserRepository().create(user)

            person['user_id'] = user.id
        
        person = person_repository.create(person)
        person_associated_repository.create(dict(person_id=current_user.person.id, associated_id=person.id))

        flash('Associado adicionado com sucesso!', 'success')


    return render_template('associated/form.html', form=form)

@associated_blueprint.route('/associados/visualizar/<person_id>', methods=['GET'])
@login_required
def show(person_id):
    person = person_repository.find(person_id)
    return render_template('associated/modals/show.html', person=person)

@associated_blueprint.route('/associados/editar/<person_id>', methods=['GET', 'POST'])
@login_required
def edit(person_id):

    person = person_repository.find(person_id)
    form = AssociatedForm(obj=person)

    if request.method == 'GET':
        email = next(person.emails, None)
        form.email.data = email.email if email else ''
        contact = next(person.contacts, None)
        form.contact.data = '{}{}'.format(contact.ddd, contact.num) if contact else ''
        return render_template('associated/modals/edit.html', form=form, person_id=person_id)

    if form.validate_on_submit():
        form.populate_obj(person)

        person.cpf = clean_id(person.cpf)
        phone = clean_id(form.contact.data)

        person = dict(person)
        person['emails'] = [form.email.data]
        person['contacts'] = [{
            'ddd': phone[0:2],
            'num': phone[2:]
        }]

        person = person_repository.update(person_id, person)

        flash('Associado atualizado com sucesso!', 'success')
    else:
        print(form.errors)
        return render_template('associated/form.html',form=form, person_id=person_id, error_edit=True)

    return redirect(url_for('associated.index'))

@associated_blueprint.route('/associados/excluir/<associated_id>', methods=['GET', 'POST'])
@login_required
def delete(associated_id):

    person_id = current_user.person.id
    person = person_repository.find(associated_id)

    if request.method == 'GET':
        return render_template('associated/modals/delete.html', person=person, person_id=associated_id)

    if request.method == 'POST':
        person_associated_repository.deleteAssociation(person_id, associated_id)

        if not person.user_id:
            person_repository.delete(associated_id)

        flash('Associado removido com sucesso!', 'success')

    return redirect(url_for('associated.index'))

backend/luna/client/templates/associated/modals/delete.html
<form id="modaldelete{{person_id}}" class="ui small form modal delete"  action="{{ url_for('associated.delete', associated_id=person_id)}}" method="post">
  <i class="close icon"></i>
  <div class="header">
    Tem certeza que deseja excluir esse associado?
  </div>
  <div class="ui content">
    <b>Essa operação não poderá ser desfeita.</b>
    <br>
    Deseja excluir <b>{{ person.name }}</b>
  </div>
  <div class="actions">
    <div class="ui cancel button">
      Cancelar
    </div>
    <div class="ui green submit button">
      Excluir
    </div>
  </div>
</form>

backend/luna/client/templates/associated/modals/edit.html
<form id="modaledit{{person_id}}" class="ui small form {{ 'error' if form.errors else '' }} modal edit"  action="{{ url_for('associated.edit', person_id=person_id)}}" method="post">
  <i class="close icon"></i>
  <div class="header">
    Editar Associado
  </div>
  <div class="ui content">
    <div class="ui error message">
      {% for (field, errors) in form.errors.items() %}
        {% for error in errors %}
          <li>{{error}}</li>
        {% endfor %}
      {% endfor %}
    </div>
    {{ form.hidden_tag() }}

      <div class="field required {{ 'error' if form.name.errors else '' }}">
        {{ form.name.label }}
        {{ form.name(placeholder=form.name.label.text) }}
      </div>
      <div class="two fields">
        <div class="field required {{ 'error' if form.cpf.errors else '' }}">
          {{ form.cpf.label }}
          {{ form.cpf(placeholder=form.cpf.label.text, data_mask='000.000.000-00') }}
        </div>
        <div class="field required {{ 'error' if form.birth.errors else '' }}">
          {{ form.birth.label }}
          {{ form.birth(placeholder=form.birth.label.text, data_mask='00/00/0000') }}
        </div>
      </div>
      <div class="field required {{ 'error' if form.email.errors else '' }}">
        {{ form.email.label }}
        {{ form.email(placeholder=form.email.label.text) }}
      </div>
      <div class="field required {{ 'error' if form.contact.errors else '' }}">
        {{ form.contact.label }}
        {{ form.contact(placeholder=form.contact.label.text, data_mask='(00) 0 0000-0000') }}
      </div>
  </div>
  <div class="actions">
    <div class="ui cancel button">
      Cancelar
    </div>
    <div class="ui green submit button">
      Editar
    </div>
  </div>
</form>

backend/luna/client/templates/associated/modals/show.html
<div id="modalshow{{person.id}}" class="ui small modal">
  <i class="close icon"></i>
  <div class="header">
    Dados do Associado
  </div>
  

    
    <section class="room">
  <table class="ui blue table">
    
    <tbody>
        <tr data-id="2">
          <td><b>Nome</b></td>
          <td><span>{{ person.name }}</span><br></td>
        </tr>
    </tbody>

    <tbody>
        <tr data-id="2">
          <td><b>CPF: </b></td>
          <td><span data-mask="000.000.000-00"></span>{{ person.cpf }}<br></td>
        </tr>
    </tbody>

    <tbody>
        <tr data-id="2">
          <td><b>Data de Nascimento: </b></td>
          <td><span data-mask="00/00/0000"></span>{{ person.birth }}<br></td>
        </tr>
    </tbody>

    <tbody>
        <tr data-id="2">
          <td><b>Facebook: </b></td>
          <td><a href="{{person.facebook}}" target="_blank">{{person.facebook}}</a><br></td>
        </tr>
    </tbody>

    <tbody>
        <tr data-id="2">
          <td><b>Twitter: </b></td>
          <td><a href="{{person.twitter}}">{{person.twitter}}</a></td>
        </tr>
    </tbody>

  </table>
</section>
    
    
    

  
  <div class="actions">
    <div class="ui blue cancel button">
      Ok
    </div>
  </div>
</form>